### ISSUE TITLE
test command should compile the project

### ISSUE THREAD

**Issue by arpunk** [clojerl/rebar3_clojerl#50]
Currently `rebar3 clojerl test` fails because the project has not been compiled:

```
 λ rebar3 clojerl test                                                                                                                                                                        
===> Verifying dependencies...
===> Linking _build/default/lib/clojerl to _build/test/lib/clojerl
===> Linking _build/default/plugins/rebar3_clojerl to _build/test/plugins/rebar3_clojerl
===> Clojerl Compiling clojerl
%%% Compiling clojure/core.clje...
%%% Compiling clojure/data.clje...
%%% Compiling clojure/core/server.clje...
%%% Compiling clojure/repl.clje...
===> Running Clojerl tests...
===> Error while testing: clojerl.Error: NO_SOURCE_FILE:?:?: Could not locate papachan.core.beam or papachan/core on code path.
```

Compiling the project as `test` fixes this:

```
 λ rebar3 as test compile && rebar3 clojerl test                                                                                                                                              
===> Verifying dependencies...
===> Compiling papachan
===> Clojerl Compiling clojerl
===> Clojerl Compiling papachan
%%% Compiling papachan/sup.clje...
%%% Compiling papachan/app.clje...
%%% Compiling papachan/core.clje...
===> Verifying dependencies...
===> Clojerl Compiling clojerl
===> Clojerl Compiling papachan
===> Running Clojerl tests...

Testing papachan.core-test

FAIL in (a-test) (/home/arpunk/papachan/_build/default/lib/clojerl/src/clj/clojure/test.clje:444)
FIXME, I fail.
expected: (= 0 1)
  actual: (not (= 0 1))

Ran 1 tests containing 1 assertions.
1 failures, 0 errors.
===> Errors: 0 - Fails: 1
===> Error while testing: :rebar_abort
```

The expected behaviour is for `rebar3 clojerl test` to precompile all the required files before running the test suite.

I am using clojerl 0.5.0 and rebar3_clojerl 0.6.6.

**Comment by jfacorro** [comment]
The `clojerl repl` depends on `clojerl compile`, but this in turn does not depend on `compile`. This is something I have been thinking for a while, but never made a decision. 

My current thinking is that if you run `rebar3 clojerl compile` it should only compile Clojerl files. So if you want `rebar3 compile` to also compile Clojerl files, you add an entry in the `provider_hooks`. This approach has its pros and cons. The main conflict I found is that since this plugin is also used to bulid Clojerl itself, and that project contains both Erlang and Clojerl files, I have struggled to find a combination that works well in both building Clojerl the language and Clojerl projects.

I was hoping at some point to find a balance between what makes sense and what would be the least surprising for the user when running the following commands (description is what they currently do):

1. `rebar3 clojerl compile`: tries to compile Clojerl files only, does not compile Erlang or any other files. 
   a. Do you think this should also try to compile Erlang files?
2. `rebar3 clojerl test`: depends on `clojerl compile` and tries to run Clojerl tests.
3. `rebar3 clojerl repl`: depends on `clojerl compile` and tries to start a Clojerl REPL.

**Comment by jfacorro** [comment]
This is now working as suggested 😄.
